export const GET_STUDENTS_PER_YEAR_REQUEST = 'GET_STUDENTS_PER_YEAR_REQUEST';
export const GET_STUDENTS_PER_YEAR_SUCCESS = 'GET_STUDENTS_PER_YEAR_SUCCESS';
export const GET_STUDENTS_PER_YEAR_FAILURE = 'GET_STUDENTS_PER_YEAR_FAILURE';

export const GET_INTERNSHIPS_REQUEST = 'GET_INTERNSHIPS_REQUEST';
export const GET_INTERNSHIPS_SUCCESS = 'GET_INTERNSHIPS_SUCCESS';
export const GET_INTERNSHIPS_FAILURE = 'GET_INTERNSHIPS_FAILURE';

export const ADD_INTERNSHIP = 'ADD_INTERNSHIP';
export const ADD_INTERNSHIP_SUCCESS = 'ADD_INTERNSHIP_SUCCESS';
export const ADD_INTERNSHIP_FAILURE = 'ADD_INTERNSHIP_FAILURE';

export const GET_OUR_RATINGS_SUCCESS = 'GET_OUR_RATINGS_SUCCESS';
export const GET_OUR_RATINGS_REQUEST = 'GET_OUR_RATINGS_REQUEST';
export const GET_OUR_RATINGS_FAILURE = 'GET_OUR_RATINGS_FAILURE';
