export const GET_STUDENTS_PER_YEAR_REQUEST = 'GET_STUDENTS_PER_YEAR_REQUEST';
export const GET_STUDENTS_PER_YEAR_SUCCESS = 'GET_STUDENTS_PER_YEAR_SUCCESS';
export const GET_STUDENTS_PER_YEAR_FAILURE = 'GET_STUDENTS_PER_YEAR_FAILURE';
