export const GET_DASHBOARD_STATISTICS_REQUEST = 'GET_DASHBOARD_STATISTICS_REQUEST';
export const GET_DASHBOARD_STATISTICS_SUCCESS = 'GET_DASHBOARD_STATISTICS_SUCCESS';
export const GET_DASHBOARD_STATISTICS_FAILURE = 'GET_DASHBOARD_STATISTICS_FAILURE';

export const GET_STUDENT_DASHBOARD_COMPANIES_REQUEST = 'GET_STUDENT_DASHBOARD_COMPANIES_REQUEST';
export const GET_STUDENT_DASHBOARD_COMPANIES_SUCCESS = 'GET_STUDENT_DASHBOARD_COMPANIES_SUCCESS';
export const GET_STUDENT_DASHBOARD_COMPANIES_FAILURE = 'GET_STUDENT_DASHBOARD_COMPANIES_FAILURE';

export const SUBSCRIBE_STUDENT_REQUEST = 'SUBSCRIBE_STUDENT_REQUEST';
export const SUBSCRIBE_STUDENT_SUCCESS = 'SUBSCRIBE_STUDENT_SUCCESS';
export const SUBSCRIBE_STUDENT_FAILURE = 'SUBSCRIBE_STUDENT_FAILURE';

export const UNSUBSCRIBE_STUDENT_REQUEST = 'UNSUBSCRIBE_STUDENT_REQUEST';
export const UNSUBSCRIBE_STUDENT_SUCCESS = 'UNSUBSCRIBE_STUDENT_SUCCESS';
export const UNSUBSCRIBE_STUDENT_FAILURE = 'UNSUBSCRIBE_STUDENT_FAILURE';