export const GET_DASHBOARD_STATISTICS_REQUEST = 'GET_DASHBOARD_STATISTICS_REQUEST';
export const GET_DASHBOARD_STATISTICS_SUCCESS = 'GET_DASHBOARD_STATISTICS_SUCCESS';
export const GET_DASHBOARD_STATISTICS_FAILURE = 'GET_DASHBOARD_STATISTICS_FAILURE';
