export const GET_STUDENT_COUNT_REQUEST = 'GET_STUDENT_COUNT_REQUEST';
export const GET_STUDENT_COUNT_SUCCESS = 'GET_STUDENT_COUNT_SUCCESS';
export const GET_STUDENT_COUNT_FAILURE = 'GET_STUDENT_COUNT_FAILURE';

export const GET_COMPANY_COUNT_REQUEST = 'GET_COMPANY_COUNT_REQUEST';
export const GET_COMPANY_COUNT_SUCCESS = 'GET_COMPANY_COUNT_SUCCESS';
export const GET_COMPANY_COUNT_FAILURE = 'GET_COMPANY_COUNT_FAILURE';

export const GET_INTERNSHIP_COUNT_REQUEST = 'GET_INTERNSHIP_COUNT_REQUEST';
export const GET_INTERNSHIP_COUNT_SUCCESS = 'GET_INTERNSHIP_COUNT_SUCCESS';
export const GET_INTERNSHIP_COUNT_FAILURE = 'GET_INTERNSHIP_COUNT_FAILURE';
