export const GET_INTERNSHIPS_FOR_STUDENT_REQUEST = 'GET_INTERNSHIPS_FOR_STUDENT_REQUEST';
export const GET_INTERNSHIPS_FOR_STUDENT_SUCCESS = 'GET_INTERNSHIPS_FOR_STUDENT_SUCCESS';
export const GET_INTERNSHIPS_FOR_STUDENT_FAILURE = 'GET_INTERNSHIPS_FOR_STUDENT_FAILURE';

export const CONFIRM_EXAM_ATTENDANCE_REQUEST = 'CONFIRM_EXAM_ATTENDANCE_REQUEST';
export const CONFIRM_EXAM_ATTENDANCE_SUCCESS = 'CONFIRM_EXAM_ATTENDANCE_SUCCESS';
export const CONFIRM_EXAM_ATTENDANCE_FAILURE = 'CONFIRM_EXAM_ATTENDANCE_FAILURE';

export const CONFIRM_INTERNSHIP_PARTICIPATION_REQUEST = 'CONFIRM_INTERNSHIP_PARTICIPATION_REQUEST';
export const CONFIRM_INTERNSHIP_PARTICIPATION_SUCCESS = 'CONFIRM_INTERNSHIP_PARTICIPATION_SUCCESS';
export const CONFIRM_INTERNSHIP_PARTICIPATION_FAILURE = 'CONFIRM_INTERNSHIP_PARTICIPATION_FAILURE';

export const REFUSE_INTERNSHIP_REQUEST = 'REFUSE_INTERNSHIP_REQUEST';
export const REFUSE_INTERNSHIP_SUCCESS = 'REFUSE_INTERNSHIP_SUCCESS';
export const REFUSE_INTERNSHIP_FAILURE = 'REFUSE_INTERNSHIP_FAILURE';
