export const WAS_PARTICIPANT_REQUEST = 'WAS_PARTICIPANT_REQUEST';
export const WAS_PARTICIPANT_SUCCESS = 'WAS_PARTICIPANT_SUCCESS';
export const WAS_PARTICIPANT_FAILURE = 'WAS_PARTICIPANT_FAILURE';

export const UPDATE_RATING_REQUEST = 'UPDATE_RATING_REQUEST';
export const UPDATE_RATING_SUCCESS = 'UPDATE_RATING_SUCCESS';
export const UPDATE_RATING_FAILURE = 'UPDATE_RATING_FAILURE';

export const ADD_TESTIMONIAL_REQUEST = 'ADD_TESTIMONIAL_REQUEST';
export const ADD_TESTIMONIAL_SUCCESS = 'ADD_TESTIMONIAL_SUCCESS';
export const ADD_TESTIMONIAL_FAILURE = 'ADD_TESTIMONIAL_FAILURE';

export const APPLY_REQUEST = 'APPLY_REQUEST';
export const APPLY_SUCCESS = 'APPLY_SUCCESS';
export const APPLY_FAILURE = 'APPLY_FAILURE';
