export const GET_INTERNSHIP_DETAILS_REQUEST = 'GET_INTERNSHIP_DETAILS_REQUEST';
export const GET_INTERNSHIP_DETAILS_SUCCESS = 'GET_INTERNSHIP_DETAILS_SUCCESS';
export const GET_INTERNSHIP_DETAILS_FAILURE = 'GET_INTERNSHIP_DETAILS_FAILURE';

export const PUT_INTERNSHIP_DETAILS_REQUEST = 'PUT_INTERNSHIP_DETAILS_REQUEST';
export const PUT_INTERNSHIP_DETAILS_SUCCESS = 'PUT_INTERNSHIP_DETAILS_SUCCESS';
export const PUT_INTERNSHIP_DETAILS_FAILURE = 'PUT_INTERNSHIP_DETAILS_FAILURE';
