export const GET_POSTS_FOR_INTERNSHIP_REQUEST = 'GET_POSTS_FOR_INTERNSHIP_REQUEST';
export const GET_POSTS_FOR_INTERNSHIP_SUCCESS = 'GET_POSTS_FOR_INTERNSHIP_SUCCESS';
export const GET_POSTS_FOR_INTERNSHIP_FAILURE = 'GET_POSTS_FOR_INTERNSHIP_FAILURE';
export const ADD_POST_FOR_INTERNSHIP_REQUEST = 'ADD_POST_FOR_INTERNSHIP_REQUEST';
export const ADD_POST_FOR_INTERNSHIP_SUCCESS = 'ADD_POST_FOR_INTERNSHIP_SUCCESS';
export const ADD_POST_FOR_INTERNSHIP_FAILURE = 'ADD_POST_FOR_INTERNSHIP_FAILURE';