export const GET_POSTS_FOR_INTERNSHIP_REQUEST = 'GET_POSTS_FOR_INTERNSHIP_REQUEST';
export const GET_POSTS_FOR_INTERNSHIP_SUCCESS = 'GET_POSTS_FOR_INTERNSHIP_SUCCESS';
export const GET_POSTS_FOR_INTERNSHIP_FAILURE = 'GET_POSTS_FOR_INTERNSHIP_FAILURE';
