export const GET_APPLICATIONS_REQUEST = 'GET_APPLICATIONS_REQUEST';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_FAILURE = 'GET_APPLICATIONS_FAILURE';

export const GET_CV_REQUEST = 'GET_CV_REQUEST';
export const GET_CV_SUCCESS = 'GET_CV_SUCCESS';
export const GET_CV_FAILURE = 'GET_CV_FAILURE';

export const GET_AVAILABILITY_REQUEST = 'GET_AVAILABILITY_REQUEST';
export const GET_AVAILABILITY_SUCCESS = 'GET_AVAILABILITY_SUCCESS';
export const GET_AVAILABILITY_FAILURE = 'GET_AVAILABILITY_FAILURE';

export const SELECT_STUDENT_REQUEST = 'SELECT_STUDENT_REQUEST';
export const SELECT_STUDENT_SUCCESS = 'SELECT_STUDENT_SUCCESS';
export const SELECT_STUDENT_FAILURE = 'SELECT_STUDENT_FAILURE';

export const APPROVE_STUDENT_REQUEST = 'APPROVE_STUDENT_REQUEST';
export const APPROVE_STUDENT_SUCCESS = 'APPROVE_STUDENT_SUCCESS';
export const APPROVE_STUDENT_FAILURE = 'APPROVE_STUDENT_FAILURE';

export const REJECT_STUDENT_REQUEST = 'REJECT_STUDENT_REQUEST';
export const REJECT_STUDENT_SUCCESS = 'REJECT_STUDENT_SUCCESS';
export const REJECT_STUDENT_FAILURE = 'REJECT_STUDENT_FAILURE';
