export const GET_APPLICATIONS_REQUEST = 'GET_APPLICATIONS_REQUEST';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_FAILURE = 'GET_APPLICATIONS_FAILURE';
export const GET_CV_REQUEST = 'GET_CV_REQUEST';
export const GET_CV_SUCCESS = 'GET_CV_SUCCESS';
export const GET_CV_FAILURE = 'GET_CV_FAILURE';